// Puzzles de ATAQUE: passe para o livre, finalizar, linha de passe, tabela, paralela, diagonal,
// pivô, bloqueio e goleiro-linha (um a mais).
import type { Puzzle } from '../tipos'
import { azul, GOL, GOLEIRO_AZUL, GOLEIRO_VERMELHO, paraJogador, paraPonto, verm } from './ajuda'

export const PUZZLES_ATAQUE: Puzzle[] = [
  {
    id: 'passe-livre',
    titulo: 'Passe para o livre',
    dificuldade: 'facil',
    categoria: 'ataque',
    contexto: 'Você está atacando. O jogo está 0 a 0.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.35, 0.5),
      azul(10, 0.55, 0.5),
      azul(7, 0.72, 0.22),
      azul(9, 0.74, 0.78),
      GOLEIRO_VERMELHO,
      verm(6, 0.5, 0.3),
      verm(5, 0.63, 0.45),
      verm(4, 0.75, 0.27),
      verm(7, 0.84, 0.52),
    ],
    bola: 'a10',
    passos: [
      {
        pergunta: 'Você é o 10, com a bola. Para quem passar?',
        opcoes: [
          {
            id: 'p7',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Passe para o 7',
            correta: false,
            explicacao: 'O 4 vermelho está colado no 7, do lado do gol.',
            consequencia: 'O 4 corta o passe e sai no contra-ataque.',
          },
          {
            id: 'p9',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Passe para o 9',
            correta: true,
            explicacao: 'O 9 está livre, sem ninguém perto, e o caminho da bola está limpo.',
          },
          {
            id: 'chute',
            jogador: 'a10',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar no gol',
            correta: false,
            explicacao: 'Muito longe, com defensores e o goleiro na frente.',
            consequencia: 'Chute fraco, fácil para o goleiro.',
          },
        ],
      },
    ],
    dica: 'Procure o companheiro que não tem nenhum vermelho perto.',
    conceito: 'Passe para quem está LIVRE (desmarcado). Antes de passar, olhe se tem um adversário perto do companheiro ou no caminho da bola.',
    rating: 650,
  },
  {
    id: 'hora-de-chutar',
    titulo: 'Hora de chutar',
    dificuldade: 'facil',
    categoria: 'ataque',
    contexto: 'Você passou do seu marcador e está perto da área.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.35, 0.5),
      azul(7, 0.6, 0.2),
      azul(10, 0.55, 0.62),
      azul(9, 0.83, 0.42),
      GOLEIRO_VERMELHO,
      verm(6, 0.45, 0.3),
      verm(8, 0.65, 0.25),
      verm(5, 0.6, 0.66),
      verm(4, 0.76, 0.46),
    ],
    bola: 'a9',
    passos: [
      {
        pergunta: 'Você é o 9 e só tem o goleiro na sua frente. E agora?',
        opcoes: [
          {
            id: 'chute',
            jogador: 'a9',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar no gol',
            correta: true,
            explicacao: 'Perto do gol, de frente e sem defensor na frente: é hora de chutar, no canto!',
          },
          {
            id: 'volta',
            jogador: 'a9',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Passe para o 10',
            correta: false,
            explicacao: 'O 10 está marcado pelo 5, e você perde a chance de gol que já tinha.',
          },
          {
            id: 'fundo',
            jogador: 'a9',
            acao: 'drible',
            alvo: paraPonto(0.93, 0.3),
            rotulo: 'Levar para a linha de fundo',
            correta: false,
            explicacao: 'Indo para o canto, o ângulo do gol fica cada vez menor e o 4 volta para marcar.',
          },
        ],
      },
    ],
    dica: 'Quem está mais perto do gol: você ou seus companheiros?',
    conceito: 'De frente para o gol, perto da área e sem defensor na frente: FINALIZE. Mire no canto, longe do goleiro.',
    rating: 700,
  },
  {
    id: 'linha-de-passe',
    titulo: 'Apareça para o passe',
    dificuldade: 'facil',
    categoria: 'ataque',
    contexto: 'O 4 está com a bola, sendo apertado pelo 9 vermelho.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.3, 0.5),
      azul(8, 0.52, 0.5),
      azul(7, 0.5, 0.12),
      azul(10, 0.75, 0.78),
      GOLEIRO_VERMELHO,
      verm(9, 0.36, 0.45),
      verm(6, 0.43, 0.5),
      verm(4, 0.6, 0.2),
      verm(5, 0.76, 0.69),
    ],
    bola: 'a4',
    passos: [
      {
        pergunta: 'Você é o 8, escondido atrás do 6 vermelho. Para onde ir para receber?',
        opcoes: [
          {
            id: 'lado',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.5, 0.76),
            rotulo: 'Ir para o lado livre',
            correta: true,
            explicacao: 'Saindo de trás do 6, o caminho da bola fica livre: agora o 4 consegue passar para você.',
          },
          {
            id: 'frente',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.63, 0.5),
            rotulo: 'Ir mais para a frente',
            correta: false,
            explicacao: 'Você continua escondido atrás do 6: a bola bate nele.',
          },
          {
            id: 'perto',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.37, 0.56),
            rotulo: 'Chegar bem perto do 4',
            correta: false,
            explicacao: 'Chegando perto, você leva o marcador junto e os dois ficam presos no mesmo lugar.',
          },
        ],
      },
    ],
    dica: 'A bola não atravessa jogador: saia de trás do vermelho.',
    conceito: 'Sem a bola, você também joga! "Dar linha de passe" é ir para um lugar onde a bola consegue chegar, sem nenhum adversário no caminho.',
    rating: 750,
  },
  {
    id: 'tabela',
    titulo: 'Tabela (toca e passa)',
    dificuldade: 'intermediario',
    categoria: 'ataque',
    contexto: 'O 5 vermelho está bem na frente do 10. Monte a jogada em 3 passos.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.35, 0.5),
      azul(10, 0.55, 0.62),
      azul(7, 0.68, 0.35),
      azul(9, 0.8, 0.2),
      GOLEIRO_VERMELHO,
      verm(8, 0.42, 0.42),
      verm(5, 0.62, 0.62),
      verm(6, 0.66, 0.24),
      verm(3, 0.84, 0.25),
    ],
    bola: 'a10',
    passos: [
      {
        pergunta: '1/3 · Você é o 10, com o 5 na sua frente. O que fazer?',
        opcoes: [
          {
            id: 'toca',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Passe para o 7',
            correta: true,
            explicacao: 'O 7 está livre e de frente: toca nele!',
          },
          {
            id: 'drible',
            jogador: 'a10',
            acao: 'drible',
            alvo: paraPonto(0.68, 0.68),
            rotulo: 'Driblar o 5',
            correta: false,
            explicacao: 'O 5 está colado e bem posicionado: o drible é arriscado.',
          },
          {
            id: 'chute',
            jogador: 'a10',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar',
            correta: false,
            explicacao: 'Longe e com o 5 na frente: o chute bate nele.',
          },
        ],
      },
      {
        pergunta: '2/3 · Você tocou. E agora, 10?',
        opcoes: [
          {
            id: 'corre',
            jogador: 'a10',
            acao: 'movimentacao',
            alvo: paraPonto(0.78, 0.66),
            rotulo: 'Correr nas costas do 5',
            correta: true,
            explicacao: 'Tocou, saiu! O 5 ficou olhando a bola e você passa por trás dele.',
          },
          {
            id: 'fica',
            jogador: 'a10',
            acao: 'movimentacao',
            alvo: paraPonto(0.5, 0.7),
            rotulo: 'Ficar parado olhando',
            correta: false,
            explicacao: 'Parado, o 5 continua te marcando e a jogada morre.',
          },
          {
            id: 'junto',
            jogador: 'a10',
            acao: 'movimentacao',
            alvo: paraPonto(0.65, 0.44),
            rotulo: 'Correr para perto do 7',
            correta: false,
            explicacao: 'Perto do 7, você leva o 5 junto e fica tudo apertado.',
          },
        ],
      },
      {
        pergunta: '3/3 · Você é o 7, com a bola. Termine a tabela!',
        opcoes: [
          {
            id: 'devolve',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Devolver para o 10',
            correta: true,
            explicacao: 'Devolve na frente do 10, que já passou do 5: ele sai na cara do gol!',
          },
          {
            id: 'chute7',
            jogador: 'a7',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar',
            correta: false,
            explicacao: 'Você está longe e o 10 está livre bem mais perto do gol.',
          },
          {
            id: 'p9',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Passe para o 9',
            correta: false,
            explicacao: 'O 3 vermelho está colado no 9.',
          },
        ],
      },
    ],
    dica: 'Tabela é: eu toco, corro, e você me devolve.',
    conceito:
      'TABELA (ou "toca e passa"): passe para um companheiro e corra para o espaço nas costas do seu marcador. O companheiro devolve a bola na sua frente. O marcador fica para trás olhando a bola!',
    rating: 950,
  },
  {
    id: 'paralela',
    titulo: 'A paralela',
    dificuldade: 'intermediario',
    categoria: 'ataque',
    contexto: 'Você está com a bola perto da linha lateral de cima.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.35, 0.5),
      azul(3, 0.45, 0.1),
      azul(8, 0.68, 0.12),
      azul(9, 0.75, 0.52),
      GOLEIRO_VERMELHO,
      verm(5, 0.6, 0.5),
      verm(2, 0.6, 0.24),
      verm(4, 0.72, 0.47),
      verm(3, 0.87, 0.4),
    ],
    bola: 'a3',
    passos: [
      {
        pergunta: 'Você é o 3. O 8 está correndo pela lateral. Qual o melhor passe?',
        opcoes: [
          {
            id: 'paralela',
            jogador: 'a3',
            acao: 'passe',
            alvo: paraPonto(0.82, 0.08),
            rotulo: 'Bola rente à linha, na frente do 8',
            correta: true,
            explicacao: 'Passe paralelo à linha lateral, no espaço à frente do 8: os defensores estão todos por dentro.',
          },
          {
            id: 'diagonal9',
            jogador: 'a3',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Passe pelo meio para o 9',
            correta: false,
            explicacao: 'O 2 está no caminho da bola e o 4 está colado no 9.',
            consequencia: 'O 2 intercepta.',
          },
          {
            id: 'conduz',
            jogador: 'a3',
            acao: 'movimentacao',
            alvo: paraPonto(0.55, 0.36),
            rotulo: 'Conduzir para o meio',
            correta: false,
            explicacao: 'Conduzindo para o meio, você vai direto para cima do 2 e do 5.',
          },
        ],
      },
    ],
    dica: 'O espaço livre está perto da linha, na frente do 8.',
    conceito: 'PARALELA: passe rente à linha lateral, no espaço à frente do companheiro que corre por ali. Funciona quando a defesa está fechando o meio.',
    rating: 1000,
  },
  {
    id: 'diagonal',
    titulo: 'A diagonal',
    dificuldade: 'intermediario',
    categoria: 'ataque',
    contexto: 'A defesa vermelha foi toda para o lado da bola.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.35, 0.4),
      azul(8, 0.55, 0.15),
      azul(7, 0.76, 0.1),
      azul(9, 0.82, 0.4),
      azul(10, 0.7, 0.8),
      GOLEIRO_VERMELHO,
      verm(5, 0.6, 0.08),
      verm(4, 0.79, 0.15),
      verm(6, 0.72, 0.33),
      verm(3, 0.86, 0.44),
    ],
    bola: 'a8',
    passos: [
      {
        pergunta: 'Você é o 8. Para onde vai a bola?',
        opcoes: [
          {
            id: 'diagonal',
            jogador: 'a8',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Passe na diagonal para o 10',
            correta: true,
            explicacao: 'Todos os vermelhos estão do lado de cima: a diagonal leva a bola para o lado vazio, onde o 10 está sozinho.',
          },
          {
            id: 'p7',
            jogador: 'a8',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Passe para o 7',
            correta: false,
            explicacao: 'O 4 está colado no 7: o lado de cima está lotado de vermelhos.',
          },
          {
            id: 'chute',
            jogador: 'a8',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar de longe',
            correta: false,
            explicacao: 'Da lateral e longe, o ângulo é pequeno e o goleiro pega fácil.',
          },
        ],
      },
    ],
    dica: 'Olhe para onde NÃO tem vermelho.',
    conceito: 'DIAGONAL: passe que atravessa a quadra para o lado oposto. Quando a defesa inteira vai para o lado da bola, o outro lado fica livre: é lá que a bola tem que chegar.',
    rating: 1050,
  },
  {
    id: 'pivo',
    titulo: 'Bola no pivô',
    dificuldade: 'intermediario',
    categoria: 'ataque',
    contexto: 'O 9 é o pivô: fica de costas para o gol, segurando o zagueiro.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.4, 0.76),
      azul(10, 0.52, 0.5),
      azul(7, 0.58, 0.18),
      azul(9, 0.8, 0.5),
      GOLEIRO_VERMELHO,
      verm(5, 0.6, 0.64),
      verm(6, 0.6, 0.3),
      verm(8, 0.45, 0.35),
      verm(3, 0.85, 0.5),
    ],
    bola: 'a10',
    passos: [
      {
        pergunta: '1/2 · Você é o 10. Como fazer a bola chegar perto do gol?',
        opcoes: [
          {
            id: 'pivo',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Passe para o pivô (9)',
            correta: true,
            explicacao: 'O caminho até o pivô está limpo. Ele segura a bola de costas enquanto o time chega.',
          },
          {
            id: 'chute',
            jogador: 'a10',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar de longe',
            correta: false,
            explicacao: 'Muito longe e com vermelhos na frente.',
          },
          {
            id: 'p7',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Passe para o 7',
            correta: false,
            explicacao: 'O 6 está perto do 7 e o passe não chega mais perto do gol.',
          },
        ],
        depois: [
          { jogador: 'a7', para: { x: 0.74, y: 0.27 } },
          { jogador: 'b6', para: { x: 0.63, y: 0.33 } },
        ],
      },
      {
        pergunta: '2/2 · Você é o pivô, com o 3 colado nas costas. O 7 vem chegando. E agora?',
        opcoes: [
          {
            id: 'escora',
            jogador: 'a9',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Escorar para o 7',
            correta: true,
            explicacao: 'O 7 chega de frente para o gol e livre: ele chuta com tudo!',
          },
          {
            id: 'gira',
            jogador: 'a9',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Girar e chutar',
            correta: false,
            explicacao: 'Com o 3 colado nas costas, girar é difícil: ele bloqueia ou rouba a bola.',
          },
          {
            id: 'drible',
            jogador: 'a9',
            acao: 'drible',
            alvo: paraPonto(0.9, 0.64),
            rotulo: 'Tentar passar pelo 3',
            correta: false,
            explicacao: 'De costas para o gol, passar pelo zagueiro sozinho quase nunca dá certo.',
          },
        ],
      },
    ],
    dica: 'O pivô é o "ponto de apoio": a bola vai nele e volta para quem chega de frente.',
    conceito:
      'PIVÔ: o jogador mais perto do gol, de costas, protegendo a bola com o corpo. Ele recebe, segura e serve o companheiro que chega de frente, que tem o gol inteiro para mirar.',
    rating: 1000,
  },
  {
    id: 'bloqueio',
    titulo: 'O bloqueio',
    dificuldade: 'avancado',
    categoria: 'ataque',
    contexto: 'O 4 vermelho não deixa o 10 avançar. O 8 pode ajudar.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.38, 0.6),
      azul(10, 0.58, 0.5),
      azul(8, 0.6, 0.28),
      azul(9, 0.84, 0.7),
      GOLEIRO_VERMELHO,
      verm(5, 0.45, 0.72),
      verm(4, 0.64, 0.5),
      verm(6, 0.64, 0.22),
      verm(3, 0.87, 0.66),
    ],
    bola: 'a10',
    passos: [
      {
        pergunta: '1/2 · Você é o 8. Como ajudar o 10 a passar pelo 4?',
        opcoes: [
          {
            id: 'bloqueia',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.645, 0.43),
            rotulo: 'Parar do lado do 4 (bloqueio)',
            correta: true,
            explicacao: 'Você para do lado do 4, parado e sem empurrar: ele fica preso atrás de você.',
          },
          {
            id: 'pede',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.48, 0.3),
            rotulo: 'Voltar e pedir a bola',
            correta: false,
            explicacao: 'Você ajuda a manter a bola, mas o 4 continua na frente do 10 e o ataque não avança.',
          },
          {
            id: 'longe',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.85, 0.12),
            rotulo: 'Correr para o canto',
            correta: false,
            explicacao: 'O 6 vai junto com você, mas o 4 continua livre para marcar o 10.',
          },
        ],
        depois: [{ jogador: 'b6', para: { x: 0.6, y: 0.36 } }],
      },
      {
        pergunta: '2/2 · Você é o 10. O 8 fez o bloqueio. Por onde ir?',
        opcoes: [
          {
            id: 'usa',
            jogador: 'a10',
            acao: 'drible',
            alvo: paraPonto(0.76, 0.34),
            rotulo: 'Conduzir pelo lado do bloqueio',
            correta: true,
            explicacao: 'Passando colado no 8, o 4 bate nele e fica para trás: caminho livre!',
          },
          {
            id: 'oposto',
            jogador: 'a10',
            acao: 'drible',
            alvo: paraPonto(0.72, 0.64),
            rotulo: 'Conduzir pelo outro lado',
            correta: false,
            explicacao: 'Do lado oposto ao bloqueio, o 4 te acompanha sem problema.',
          },
          {
            id: 'p8',
            jogador: 'a10',
            acao: 'passe',
            alvo: paraJogador('a8'),
            rotulo: 'Passe para o 8',
            correta: false,
            explicacao: 'O 8 está parado, no meio de dois vermelhos.',
          },
        ],
      },
    ],
    dica: 'O bloqueio é um "muro" parado ao lado do marcador.',
    conceito:
      'BLOQUEIO (corta-luz): um companheiro para do lado do marcador, sem empurrar. Quem tem a bola passa colado nele e o marcador fica preso. Precisa combinar: um bloqueia, o outro usa.',
    rating: 1250,
  },
  {
    id: 'goleiro-linha',
    titulo: 'Um a mais: goleiro-linha',
    dificuldade: 'avancado',
    categoria: 'ataque',
    contexto: 'Faltam 2 minutos, vocês perdem por 1 a 0. O goleiro virou jogador de linha (o 12): são 5 contra 4.',
    jogadores: [
      azul(12, 0.55, 0.5),
      azul(2, 0.62, 0.15),
      azul(5, 0.62, 0.88),
      azul(8, 0.8, 0.22),
      azul(9, 0.84, 0.68),
      GOLEIRO_VERMELHO,
      verm(4, 0.75, 0.24),
      verm(5, 0.7, 0.42),
      verm(6, 0.72, 0.62),
      verm(3, 0.87, 0.63),
    ],
    bola: 'a2',
    passos: [
      {
        pergunta: '1/2 · Você é o 2. Comece a rodar a bola.',
        opcoes: [
          {
            id: 'meio',
            jogador: 'a2',
            acao: 'passe',
            alvo: paraJogador('a12'),
            rotulo: 'Passe para o 12, no meio',
            correta: true,
            explicacao: 'O 12 está livre no meio. A bola rodando faz a defesa se mexer e abrir espaço.',
          },
          {
            id: 'p8',
            jogador: 'a2',
            acao: 'passe',
            alvo: paraJogador('a8'),
            rotulo: 'Passe para o 8',
            correta: false,
            explicacao: 'O 4 está colado no 8.',
          },
          {
            id: 'chute',
            jogador: 'a2',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar',
            correta: false,
            explicacao: 'Longe e da lateral: perde a bola e o gol de vocês está vazio!',
            consequencia: 'O goleiro pega e chuta direto para o gol vazio.',
          },
        ],
        depois: [
          { jogador: 'b5', para: { x: 0.64, y: 0.46 } },
          { jogador: 'b6', para: { x: 0.68, y: 0.5 } },
          { jogador: 'b4', para: { x: 0.72, y: 0.3 } },
        ],
      },
      {
        pergunta: '2/2 · Você é o 12. A defesa veio para o meio. Quem está livre?',
        opcoes: [
          {
            id: 'p5',
            jogador: 'a12',
            acao: 'passe',
            alvo: paraJogador('a5'),
            rotulo: 'Passe para o 5',
            correta: true,
            explicacao: 'Os vermelhos fecharam o meio e o 5 ficou sozinho do lado de baixo.',
          },
          {
            id: 'p9',
            jogador: 'a12',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Passe para o 9',
            correta: false,
            explicacao: 'O 3 está bem perto do 9.',
          },
          {
            id: 'p8b',
            jogador: 'a12',
            acao: 'passe',
            alvo: paraJogador('a8'),
            rotulo: 'Passe para o 8',
            correta: false,
            explicacao: 'O 4 continua perto do 8 e o 5 vermelho está no caminho.',
          },
        ],
      },
    ],
    dica: 'Com um jogador a mais, sempre tem alguém livre. Procure longe de onde a defesa foi.',
    conceito:
      'GOLEIRO-LINHA: com 5 contra 4, sempre sobra um livre. Toque rápido e paciente até encontrá-lo, de preferência do lado oposto ao que a defesa foi. Cuidado: perder a bola deixa o seu gol vazio.',
    rating: 1300,
  },
]
