// Puzzles de BOLA PARADA: reposição do goleiro, lateral e escanteio.
import type { Puzzle } from '../tipos'
import { azul, GOLEIRO_VERMELHO, paraJogador, verm } from './ajuda'

export const PUZZLES_BOLA_PARADA: Puzzle[] = [
  {
    id: 'reposicao-lado-livre',
    titulo: 'Goleiro: para o lado livre',
    dificuldade: 'facil',
    categoria: 'bola-parada',
    contexto: 'Bola com o seu goleiro. O 9 vermelho está pressionando no meio.',
    jogadores: [
      azul(1, 0.06, 0.5, true),
      azul(4, 0.2, 0.15),
      azul(6, 0.2, 0.85),
      azul(8, 0.45, 0.3),
      azul(10, 0.55, 0.52),
      GOLEIRO_VERMELHO,
      verm(9, 0.2, 0.5),
      verm(8, 0.24, 0.19),
      verm(6, 0.42, 0.34),
      verm(5, 0.5, 0.5),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro. Para quem jogar?',
        opcoes: [
          {
            id: 'p4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Para o 4',
            correta: false,
            explicacao: 'O 8 vermelho está colado no 4.',
          },
          {
            id: 'p6',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a6'),
            rotulo: 'Para o 6',
            correta: true,
            explicacao: 'O 6 está livre, longe do 9 vermelho: saída de bola segura.',
          },
          {
            id: 'chutao',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Chutão pelo meio para o 10',
            correta: false,
            explicacao: 'Pelo meio, o 9 e o 5 vermelhos estão no caminho: a bola é roubada perto do seu gol.',
            consequencia: 'Roubada perto da área: perigo!',
          },
        ],
      },
    ],
    dica: 'Para onde o 9 vermelho NÃO está olhando?',
    conceito: 'O goleiro repõe a bola para o lado LIVRE, pelo canto, e nunca pelo meio quando tem adversário lá. Perder a bola perto do próprio gol é o maior perigo.',
    rating: 650,
  },
  {
    id: 'lateral-curto',
    titulo: 'Lateral: 4 segundos!',
    dificuldade: 'intermediario',
    categoria: 'bola-parada',
    contexto: 'Tiro lateral para vocês. No futsal você tem 4 segundos para cobrar, com o pé.',
    jogadores: [
      azul(1, 0.04, 0.5, true),
      azul(4, 0.4, 0.02),
      azul(6, 0.5, 0.13),
      azul(8, 0.62, 0.1),
      azul(9, 0.76, 0.46),
      GOLEIRO_VERMELHO,
      verm(6, 0.43, 0.27),
      verm(8, 0.64, 0.15),
      verm(4, 0.78, 0.5),
      verm(9, 0.3, 0.3),
    ],
    bola: 'a4',
    passos: [
      {
        pergunta: 'Você é o 4, cobrando o lateral. Para quem passar?',
        opcoes: [
          {
            id: 'p6',
            jogador: 'a4',
            acao: 'passe',
            alvo: paraJogador('a6'),
            rotulo: 'Passe curto para o 6',
            correta: true,
            explicacao: 'O 6 se mexeu e escapou do marcador: passe curto, rápido e seguro.',
          },
          {
            id: 'p8',
            jogador: 'a4',
            acao: 'passe',
            alvo: paraJogador('a8'),
            rotulo: 'Passe para o 8',
            correta: false,
            explicacao: 'O 8 vermelho está grudado no 8 azul.',
          },
          {
            id: 'p9',
            jogador: 'a4',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Bola longa para o 9',
            correta: false,
            explicacao: 'Bola longa demora para chegar e o 4 vermelho está colado no 9.',
          },
        ],
      },
    ],
    dica: 'Quem saiu de perto do seu marcador?',
    conceito: 'No LATERAL, quem vai receber se mexe para escapar da marcação e chega perto. O passe curto e rápido é o mais seguro: são só 4 segundos para cobrar!',
    rating: 1100,
  },
  {
    id: 'escanteio-rasteiro',
    titulo: 'Escanteio ensaiado',
    dificuldade: 'avancado',
    categoria: 'bola-parada',
    contexto: 'Escanteio para vocês. Na área, os vermelhos marcam forte.',
    jogadores: [
      azul(1, 0.08, 0.5, true),
      azul(7, 0.99, 0.02),
      azul(10, 0.7, 0.32),
      azul(4, 0.9, 0.21),
      azul(9, 0.9, 0.42),
      GOLEIRO_VERMELHO,
      verm(4, 0.88, 0.25),
      verm(3, 0.88, 0.46),
      verm(5, 0.93, 0.38),
      verm(6, 0.75, 0.62),
    ],
    bola: 'a7',
    passos: [
      {
        pergunta: 'Você é o 7, cobrando o escanteio. Qual a melhor jogada?',
        opcoes: [
          {
            id: 'rasteiro10',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Rasteiro para o 10, fora da área',
            correta: true,
            explicacao: 'O 10 está livre e chega de frente para a bola: recebe e chuta de primeira.',
          },
          {
            id: 'alto9',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Bola alta para o 9 na área',
            correta: false,
            explicacao: 'O 9 tem dois marcadores e o goleiro pode sair para pegar a bola.',
          },
          {
            id: 'curto4',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Curto para o 4',
            correta: false,
            explicacao: 'O 4 está marcado e de costas para o gol.',
          },
        ],
      },
    ],
    dica: 'No futsal, a bola alta quase nunca é a melhor. Quem está livre e de frente?',
    conceito: 'No ESCANTEIO do futsal, a jogada mais perigosa costuma ser rasteira, para quem chega de trás, de frente para a bola, e chuta de primeira.',
    rating: 1200,
  },
]
