// Puzzles de DEFESA: entre a bola e o gol, dobra, goleiro fechando o ângulo e 2 contra 1.
// Aqui o time vermelho ataca o SEU gol (o da esquerda).
import type { Puzzle } from '../tipos'
import { azul, GOLEIRO_AZUL, GOLEIRO_VERMELHO, paraJogador, paraPonto, verm } from './ajuda'

export const PUZZLES_DEFESA: Puzzle[] = [
  {
    id: 'entre-bola-e-gol',
    titulo: 'Entre a bola e o gol',
    dificuldade: 'facil',
    categoria: 'defesa',
    contexto: 'O 9 vermelho vem com a bola na direção do seu gol.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(5, 0.4, 0.58),
      azul(4, 0.42, 0.82),
      azul(8, 0.6, 0.48),
      azul(10, 0.72, 0.3),
      GOLEIRO_VERMELHO,
      verm(9, 0.32, 0.35),
      verm(7, 0.46, 0.75),
      verm(10, 0.55, 0.4),
      verm(4, 0.8, 0.55),
    ],
    bola: 'b9',
    passos: [
      {
        pergunta: 'Você é o 5. O que fazer?',
        opcoes: [
          {
            id: 'entre',
            jogador: 'a5',
            acao: 'movimentacao',
            alvo: paraPonto(0.22, 0.4),
            rotulo: 'Ficar entre ele e o gol',
            correta: true,
            explicacao: 'Na frente do gol, você fecha o caminho e ele precisa passar por você.',
          },
          {
            id: 'carrinho',
            jogador: 'a5',
            acao: 'desarme',
            alvo: paraJogador('b9'),
            rotulo: 'Dar um carrinho de longe',
            correta: false,
            explicacao: 'De longe, ele desvia fácil, e um carrinho pode ser falta.',
            consequencia: 'Ele passa e fica sozinho com o goleiro.',
          },
          {
            id: 'marca7',
            jogador: 'a5',
            acao: 'marcacao',
            alvo: paraJogador('b7'),
            rotulo: 'Marcar o 7',
            correta: false,
            explicacao: 'O 4 já está perto do 7. Se você for também, o caminho até o gol fica livre para o 9.',
          },
        ],
      },
    ],
    dica: 'Imagine uma linha da bola até o meio do seu gol.',
    conceito: 'Na defesa, fique SEMPRE entre a bola e o seu gol. Assim o atacante tem que passar por você para chegar lá.',
    rating: 700,
  },
  {
    id: 'dobra',
    titulo: 'A dobra',
    dificuldade: 'intermediario',
    categoria: 'defesa',
    contexto: 'O 7 vermelho está com a bola no canto, perto da linha, e o 3 está marcando ele.',
    jogadores: [
      azul(1, 0.03, 0.45, true),
      azul(3, 0.16, 0.14),
      azul(5, 0.3, 0.26),
      azul(8, 0.26, 0.56),
      azul(4, 0.5, 0.62),
      GOLEIRO_VERMELHO,
      verm(7, 0.12, 0.07),
      verm(9, 0.31, 0.56),
      verm(10, 0.62, 0.36),
      verm(4, 0.62, 0.68),
    ],
    bola: 'b7',
    passos: [
      {
        pergunta: 'Você é o 5. Qual a melhor ajuda?',
        opcoes: [
          {
            id: 'dobra',
            jogador: 'a5',
            acao: 'marcacao',
            alvo: paraJogador('b7'),
            rotulo: 'Fechar o 7 junto com o 3',
            correta: true,
            explicacao: 'Ele está preso entre a linha e o canto. Com dois em cima, não tem para onde ir e perde a bola.',
          },
          {
            id: 'marca9',
            jogador: 'a5',
            acao: 'marcacao',
            alvo: paraJogador('b9'),
            rotulo: 'Marcar o 9',
            correta: false,
            explicacao: 'O 8 já marca o 9. Dois no mesmo jogador e o 7 fica com tempo para sair jogando.',
          },
          {
            id: 'espera',
            jogador: 'a5',
            acao: 'movimentacao',
            alvo: paraPonto(0.34, 0.3),
            rotulo: 'Esperar no lugar',
            correta: false,
            explicacao: 'Esperando, o 7 tem tempo de levantar a cabeça e tocar.',
          },
        ],
      },
    ],
    dica: 'A linha lateral é como um "defensor a mais" que ajuda você.',
    conceito:
      'DOBRA: quando o adversário está preso perto da linha ou do canto, um segundo defensor vai junto e os dois roubam a bola. Só dá certo se os outros companheiros estiverem bem marcados.',
    rating: 1050,
  },
  {
    id: 'goleiro-angulo',
    titulo: 'Goleiro: fechar o ângulo',
    dificuldade: 'avancado',
    categoria: 'defesa',
    contexto: 'O 9 vermelho passou de todo mundo e vai chutar da diagonal.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.32, 0.4),
      azul(5, 0.4, 0.7),
      azul(8, 0.6, 0.5),
      azul(10, 0.7, 0.3),
      GOLEIRO_VERMELHO,
      verm(9, 0.2, 0.25),
      verm(7, 0.45, 0.6),
      verm(10, 0.55, 0.35),
      verm(4, 0.8, 0.5),
    ],
    bola: 'b9',
    passos: [
      {
        pergunta: 'Você é o goleiro (1). Para onde ir?',
        opcoes: [
          {
            id: 'linha',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.06, 0.43),
            rotulo: 'Sair um pouco, na linha da bola',
            correta: true,
            explicacao: 'Na linha entre a bola e o meio do gol, um pouco à frente: os dois cantos ficam pequenos para ele.',
          },
          {
            id: 'poste',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.02, 0.62),
            rotulo: 'Ir para o poste de baixo',
            correta: false,
            explicacao: 'Indo para o poste longe dele, o canto perto (de cima) fica todo aberto.',
          },
          {
            id: 'sai',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.15, 0.31),
            rotulo: 'Correr até ele',
            correta: false,
            explicacao: 'Saindo correndo lá longe, um toque por cima ou para o lado e o gol fica vazio.',
          },
        ],
      },
    ],
    dica: 'Ligue a bola ao meio do seu gol com uma linha imaginária.',
    conceito:
      'O goleiro se coloca na LINHA entre a bola e o meio do gol, e sai um pouco para a frente. Assim "fecha o ângulo": sobra menos gol para o atacante mirar. Sair demais deixa ele te encobrir.',
    rating: 1200,
  },
  {
    id: 'dois-contra-um',
    titulo: 'Defender 2 contra 1',
    dificuldade: 'avancado',
    categoria: 'defesa',
    contexto: 'Contra-ataque vermelho: o 7 e o 10 contra você e o goleiro. O 8 azul vem voltando.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.2, 0.5),
      azul(8, 0.58, 0.5),
      azul(5, 0.75, 0.3),
      azul(10, 0.8, 0.7),
      GOLEIRO_VERMELHO,
      verm(7, 0.33, 0.32),
      verm(10, 0.31, 0.72),
      verm(9, 0.65, 0.42),
      verm(4, 0.85, 0.5),
    ],
    bola: 'b7',
    passos: [
      {
        pergunta: 'Você é o 4, sozinho contra dois. O que fazer?',
        opcoes: [
          {
            id: 'temporiza',
            jogador: 'a4',
            acao: 'movimentacao',
            alvo: paraPonto(0.16, 0.54),
            rotulo: 'Ficar entre os dois, recuando',
            correta: true,
            explicacao: 'Entre os dois, você atrapalha o passe e ganha tempo até o 8 voltar. O goleiro fica com quem chutar.',
          },
          {
            id: 'bote',
            jogador: 'a4',
            acao: 'desarme',
            alvo: paraJogador('b7'),
            rotulo: 'Dar o bote no 7',
            correta: false,
            explicacao: 'Ao sair no 7, ele toca para o 10, que fica livre na cara do gol.',
            consequencia: 'Gol do 10.',
          },
          {
            id: 'marca10',
            jogador: 'a4',
            acao: 'marcacao',
            alvo: paraJogador('b10'),
            rotulo: 'Colar no 10',
            correta: false,
            explicacao: 'Colando no 10, o 7 entra livre com a bola até o goleiro.',
          },
        ],
      },
    ],
    dica: 'Sozinho contra dois, ganhar tempo vale mais que roubar a bola.',
    conceito:
      'Em INFERIORIDADE (1 contra 2), o defensor não se joga: fica entre os dois, recuando, para atrapalhar o passe e esperar ajuda. O goleiro cuida de quem chutar.',
    rating: 1350,
  },
]
