// Puzzles de SAÍDA DE BOLA DO GOLEIRO: depois de uma defesa (transição) e no tiro de meta
// (bola parada). Ensinam também as regras que mais pegam no futsal: 4 segundos com a bola no
// próprio campo e o goleiro não poder tocar de novo na bola, no próprio campo, depois de jogá-la.
import type { Puzzle } from '../tipos'
import { azul, GOLEIRO_VERMELHO, paraJogador, paraPonto, verm } from './ajuda'

export const PUZZLES_SAIDA_GOLEIRO: Puzzle[] = [
  // ---------- Saída depois de uma defesa ----------
  {
    id: 'saida-defesa-calma',
    titulo: 'Defendeu! Rápido ou com calma?',
    dificuldade: 'facil',
    categoria: 'transicao',
    contexto: 'Você agarrou a bola. O time vermelho já voltou todo para o campo dele e está esperando.',
    jogadores: [
      azul(1, 0.05, 0.5, true),
      azul(4, 0.18, 0.72),
      azul(6, 0.3, 0.22),
      azul(7, 0.45, 0.82),
      azul(9, 0.72, 0.5),
      GOLEIRO_VERMELHO,
      verm(9, 0.54, 0.5),
      verm(4, 0.6, 0.25),
      verm(5, 0.62, 0.75),
      verm(3, 0.77, 0.52),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro (1). Não tem contra-ataque. O que fazer?',
        opcoes: [
          {
            id: 'curto4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Rolar curto para o 4',
            correta: true,
            explicacao: 'Sem chance de contra-ataque, o melhor é sair jogando com calma: passe curto e seguro para quem está livre.',
          },
          {
            id: 'longo9',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Lançar longe para o 9',
            correta: false,
            explicacao: 'O 9 está no meio de dois vermelhos: a bola longa fica dividida e vocês perdem a posse.',
          },
          {
            id: 'segura',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.1, 0.5),
            rotulo: 'Ficar com a bola esperando',
            correta: false,
            explicacao: 'O goleiro só pode ficar 4 segundos com a bola no próprio campo. Passou disso, é falta!',
            consequencia: 'Tiro livre indireto para o time vermelho, pertinho do seu gol.',
          },
        ],
      },
    ],
    dica: 'Quando o adversário já está todo arrumado, não adianta correr. E lembre: 4 segundos!',
    conceito:
      'Depois de uma defesa, o goleiro olha primeiro se dá para contra-atacar. Se o adversário já voltou, sai jogando curto, com calma, para não perder a bola. E nunca passe de 4 segundos com a bola no seu campo.',
    rating: 750,
  },
  {
    id: 'saida-defesa-espaco',
    titulo: 'Lançamento no espaço',
    dificuldade: 'intermediario',
    categoria: 'transicao',
    contexto: 'Você defendeu um chute. Três vermelhos ainda estão no seu campo, e o 7 azul já saiu correndo pela lateral.',
    jogadores: [
      azul(1, 0.05, 0.5, true),
      azul(4, 0.2, 0.6),
      azul(8, 0.35, 0.86),
      azul(7, 0.42, 0.12),
      azul(9, 0.6, 0.7),
      GOLEIRO_VERMELHO,
      verm(9, 0.18, 0.42),
      verm(7, 0.25, 0.7),
      verm(10, 0.32, 0.42),
      verm(4, 0.64, 0.52),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro. Como lançar para o 7?',
        opcoes: [
          {
            id: 'espaco',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraPonto(0.6, 0.1),
            rotulo: 'No espaço, na frente do 7',
            correta: true,
            explicacao: 'Com a bola na frente, o 7 continua correndo sem frear: ninguém alcança e ele sai na cara do gol.',
          },
          {
            id: 'pe',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'No pé do 7',
            correta: false,
            explicacao: 'No pé, o 7 precisa parar para dominar. O 10 vermelho tem tempo de voltar e chegar nele.',
          },
          {
            id: 'curto',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Rolar para o 4',
            correta: false,
            explicacao: 'O 4 está entre o 9 e o 7 vermelhos: perigo de perder a bola perto do seu gol, e o contra-ataque some.',
          },
        ],
      },
    ],
    dica: 'Quem está correndo gosta de receber a bola na frente, não para trás.',
    conceito:
      'No contra-ataque, o goleiro lança a bola no ESPAÇO à frente do companheiro que corre, e não no pé dele. Assim ele não perde velocidade e o adversário não consegue voltar a tempo.',
    rating: 950,
  },
  {
    id: 'saida-defesa-ler-o-jogo',
    titulo: 'Saída após defesa: leia o jogo',
    dificuldade: 'avancado',
    categoria: 'transicao',
    contexto: 'Você defendeu. O 9 e o 7 vermelhos ainda estão perto da sua área. Monte a saída em 2 jogadas.',
    jogadores: [
      azul(1, 0.05, 0.5, true),
      azul(4, 0.2, 0.56),
      azul(10, 0.4, 0.4),
      azul(8, 0.45, 0.8),
      azul(9, 0.75, 0.22),
      GOLEIRO_VERMELHO,
      verm(9, 0.14, 0.33),
      verm(7, 0.17, 0.68),
      verm(10, 0.44, 0.35),
      verm(4, 0.76, 0.52),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: '1/2 · Você é o goleiro. Para onde vai a bola?',
        opcoes: [
          {
            id: 'lanca8',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a8'),
            rotulo: 'Lançar para o 8, longe da área',
            correta: true,
            explicacao: 'O 8 está livre e longe dos atacantes vermelhos: a bola sai da zona de perigo e o time ataca.',
          },
          {
            id: 'rola4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Rolar para o 4, pertinho',
            correta: false,
            explicacao: 'O 9 e o 7 vermelhos ainda estão bem ali: se roubarem, é gol na cara do goleiro.',
            consequencia: 'Bola roubada dentro da sua área.',
          },
          {
            id: 'segura',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.1, 0.5),
            rotulo: 'Segurar e esperar',
            correta: false,
            explicacao: 'Esperando, o time vermelho volta todo e você ainda arrisca estourar os 4 segundos.',
          },
        ],
        depois: [
          { jogador: 'a10', para: { x: 0.62, y: 0.44 } },
          { jogador: 'b9', para: { x: 0.24, y: 0.36 } },
          { jogador: 'b7', para: { x: 0.28, y: 0.64 } },
        ],
      },
      {
        pergunta: '2/2 · Você é o 8, com a bola. O 10 atacou o meio. E agora?',
        opcoes: [
          {
            id: 'p10',
            jogador: 'a8',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Passe para o 10',
            correta: true,
            explicacao: 'O 10 passou do marcador e vai de frente para o gol: agora são 2 azuis contra o 4 vermelho.',
          },
          {
            id: 'volta1',
            jogador: 'a8',
            acao: 'passe',
            alvo: paraJogador('a1'),
            rotulo: 'Devolver para o goleiro',
            correta: false,
            explicacao: 'Não pode! Depois que o goleiro joga a bola, ele não pode tocar nela de novo no próprio campo até um adversário tocar.',
            consequencia: 'Falta: tiro livre indireto para o time vermelho.',
          },
          {
            id: 'sozinho',
            jogador: 'a8',
            acao: 'movimentacao',
            alvo: paraPonto(0.7, 0.9),
            rotulo: 'Conduzir sozinho pela lateral',
            correta: false,
            explicacao: 'O 4 vermelho fecha a lateral e o resto do time deles tem tempo de voltar.',
          },
        ],
      },
    ],
    dica: 'Primeiro, tire a bola de perto dos atacantes deles. Depois, procure quem ataca o meio.',
    conceito:
      'Depois da defesa, o goleiro LÊ o jogo: se ainda há atacantes perto da área, a bola vai para longe deles. E atenção à regra: o goleiro que já jogou a bola não pode tocar nela de novo no próprio campo até um adversário tocar.',
    rating: 1200,
  },

  // ---------- Tiro de meta (o goleiro repõe com a mão) ----------
  {
    id: 'tiro-de-meta-4-segundos',
    titulo: 'Tiro de meta: 4 segundos!',
    dificuldade: 'facil',
    categoria: 'bola-parada',
    contexto: 'Tiro de meta para vocês. No futsal, o goleiro repõe com a MÃO e tem só 4 segundos.',
    jogadores: [
      azul(1, 0.08, 0.5, true),
      azul(4, 0.2, 0.85),
      azul(6, 0.25, 0.15),
      azul(10, 0.4, 0.5),
      azul(9, 0.7, 0.5),
      GOLEIRO_VERMELHO,
      verm(8, 0.28, 0.19),
      verm(9, 0.36, 0.45),
      verm(5, 0.44, 0.56),
      verm(3, 0.74, 0.5),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro, com a bola na mão. O que fazer?',
        opcoes: [
          {
            id: 'lanca4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Lançar para o 4',
            correta: true,
            explicacao: 'O 4 está livre, perto da lateral e longe dos vermelhos: reposição rápida e segura.',
          },
          {
            id: 'lanca10',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Lançar para o 10, no meio',
            correta: false,
            explicacao: 'O 10 está entre o 9 e o 5 vermelhos. Perder a bola no meio, perto do seu gol, é muito perigoso.',
          },
          {
            id: 'espera',
            jogador: 'a1',
            acao: 'movimentacao',
            alvo: paraPonto(0.1, 0.42),
            rotulo: 'Esperar todo mundo se arrumar',
            correta: false,
            explicacao: 'O árbitro conta 4 segundos! Se o goleiro não repuser a bola a tempo, é falta.',
            consequencia: 'Tiro livre indireto para o time vermelho, na entrada da sua área.',
          },
        ],
      },
    ],
    dica: 'Rápido e para quem está livre. Conte: 1, 2, 3, 4...',
    conceito:
      'No TIRO DE META do futsal, o goleiro repõe a bola com a mão, de dentro da área, em até 4 segundos. Os adversários ficam fora da área até a bola estar em jogo. Procure o companheiro livre, de preferência pelo lado.',
    rating: 700,
  },
  {
    id: 'tiro-de-meta-desmarque',
    titulo: 'Tiro de meta contra a pressão',
    dificuldade: 'intermediario',
    categoria: 'bola-parada',
    contexto: 'Tiro de meta para vocês. Os vermelhos marcam cada azul de perto, "homem a homem".',
    jogadores: [
      azul(1, 0.08, 0.5, true),
      azul(7, 0.22, 0.24),
      azul(4, 0.22, 0.72),
      azul(10, 0.4, 0.5),
      azul(9, 0.7, 0.5),
      GOLEIRO_VERMELHO,
      verm(8, 0.26, 0.28),
      verm(9, 0.26, 0.68),
      verm(10, 0.36, 0.5),
      verm(3, 0.74, 0.5),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: '1/2 · Ninguém está livre. Você é o 7: como ajudar o goleiro?',
        opcoes: [
          {
            id: 'abre',
            jogador: 'a7',
            acao: 'movimentacao',
            alvo: paraPonto(0.18, 0.07),
            rotulo: 'Abrir no canto, perto da linha',
            correta: true,
            explicacao: 'Saindo rápido para o canto, você escapa do 8 e fica num lugar onde ninguém corta o lançamento.',
          },
          {
            id: 'area',
            jogador: 'a7',
            acao: 'movimentacao',
            alvo: paraPonto(0.12, 0.32),
            rotulo: 'Entrar na área, perto do goleiro',
            correta: false,
            explicacao: 'O 8 vem junto. E se ele roubar a bola ali, é gol na hora.',
          },
          {
            id: 'parado',
            jogador: 'a7',
            acao: 'movimentacao',
            alvo: paraPonto(0.24, 0.2),
            rotulo: 'Ficar parado pedindo a bola',
            correta: false,
            explicacao: 'Parado, o 8 continua colado em você: o goleiro não tem para quem jogar.',
          },
        ],
        depois: [{ jogador: 'b8', para: { x: 0.28, y: 0.17 } }],
      },
      {
        pergunta: '2/2 · Você é o goleiro. Para quem repor?',
        opcoes: [
          {
            id: 'p7',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a7'),
            rotulo: 'Para o 7, no canto',
            correta: true,
            explicacao: 'O 7 se desmarcou: lançamento curto, pelo lado, sem ninguém no caminho.',
          },
          {
            id: 'p4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Para o 4',
            correta: false,
            explicacao: 'O 9 vermelho continua colado no 4.',
          },
          {
            id: 'p10',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Para o 10, no meio',
            correta: false,
            explicacao: 'O 10 vermelho está bem na frente dele, no meio: o pior lugar para perder a bola.',
          },
        ],
      },
    ],
    dica: 'O goleiro precisa de ajuda: alguém tem que se mexer para ficar livre.',
    conceito:
      'Contra a pressão, o tiro de meta é trabalho de TODO o time: os jogadores se mexem para fugir do marcador e dar uma opção segura, de preferência aberta, perto da lateral. O goleiro escolhe quem se desmarcou.',
    rating: 1000,
  },
  {
    id: 'tiro-de-meta-inverter',
    titulo: 'Tiro de meta: o outro lado',
    dificuldade: 'avancado',
    categoria: 'bola-parada',
    contexto: 'Tiro de meta para vocês. Três vermelhos fecharam o lado de cima, onde a bola costuma ir.',
    jogadores: [
      azul(1, 0.08, 0.5, true),
      azul(4, 0.22, 0.2),
      azul(7, 0.4, 0.12),
      azul(9, 0.55, 0.45),
      azul(6, 0.3, 0.88),
      GOLEIRO_VERMELHO,
      verm(9, 0.25, 0.25),
      verm(10, 0.32, 0.32),
      verm(8, 0.42, 0.17),
      verm(3, 0.59, 0.45),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro. Para onde repor?',
        opcoes: [
          {
            id: 'p6',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a6'),
            rotulo: 'Para o 6, do outro lado',
            correta: true,
            explicacao: 'A pressão foi toda para cima. Do lado de baixo, o 6 está sozinho e com espaço para avançar.',
          },
          {
            id: 'p4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Rolar para o 4',
            correta: false,
            explicacao: 'O 9 e o 10 vermelhos estão em cima do 4: é exatamente onde eles querem roubar.',
          },
          {
            id: 'p9',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Lançar no pivô (9)',
            correta: false,
            explicacao: 'O 9 está de costas e marcado no meio da quadra. Se perder ali, o contra-ataque vem de frente para o seu gol.',
          },
        ],
      },
    ],
    dica: 'Olhe para o lado onde NÃO tem vermelho.',
    conceito:
      'Quando o adversário lota um lado para pressionar o tiro de meta, o goleiro INVERTE: repõe no lado oposto, onde sobrou espaço. Evite o meio da quadra: perder a bola ali deixa o seu gol exposto.',
    rating: 1150,
  },
]
