// Puzzles de TRANSIÇÃO: contra-ataque saindo do goleiro, 2 contra 1 e recomposição (voltar a
// defender quando perde a bola).
import type { Puzzle } from '../tipos'
import { azul, GOL, GOLEIRO_AZUL, GOLEIRO_VERMELHO, paraJogador, paraPonto, verm } from './ajuda'

export const PUZZLES_TRANSICAO: Puzzle[] = [
  {
    id: 'contra-ataque-do-goleiro',
    titulo: 'Goleiro começa o contra-ataque',
    dificuldade: 'facil',
    categoria: 'transicao',
    contexto: 'Você é o goleiro e acabou de agarrar a bola. O time vermelho está quase todo no seu campo.',
    jogadores: [
      azul(1, 0.05, 0.5, true),
      azul(4, 0.15, 0.62),
      azul(5, 0.22, 0.27),
      azul(8, 0.3, 0.82),
      azul(9, 0.75, 0.2),
      GOLEIRO_VERMELHO,
      verm(9, 0.2, 0.47),
      verm(10, 0.3, 0.18),
      verm(7, 0.28, 0.7),
      verm(4, 0.62, 0.52),
    ],
    bola: 'a1',
    passos: [
      {
        pergunta: 'Você é o goleiro (1). Para quem jogar a bola?',
        opcoes: [
          {
            id: 'lanca9',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a9'),
            rotulo: 'Lançar com a mão para o 9',
            correta: true,
            explicacao: 'O 9 ficou lá na frente e só tem um vermelho perto: lançando rápido, ele sai no contra-ataque.',
          },
          {
            id: 'p4',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a4'),
            rotulo: 'Rolar para o 4',
            correta: false,
            explicacao: 'O 9 vermelho está bem do lado do 4, e o time vermelho tem tempo de voltar.',
          },
          {
            id: 'p5',
            jogador: 'a1',
            acao: 'passe',
            alvo: paraJogador('a5'),
            rotulo: 'Rolar para o 5',
            correta: false,
            explicacao: 'O 10 vermelho está perto do 5 e pode cortar.',
          },
        ],
      },
    ],
    dica: 'Quem está mais perto do gol deles e com espaço?',
    conceito: 'Quando o adversário ataca com muita gente, ele deixa espaço atrás. Se o goleiro repõe a bola RÁPIDO no companheiro livre lá na frente, sai um contra-ataque.',
    rating: 850,
  },
  {
    id: 'dois-contra-um-ataque',
    titulo: 'Contra-ataque 2 contra 1',
    dificuldade: 'intermediario',
    categoria: 'transicao',
    contexto: 'Vocês roubaram a bola: o 7 e o 10 contra um defensor só.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.3, 0.6),
      azul(7, 0.6, 0.42),
      azul(10, 0.6, 0.78),
      GOLEIRO_VERMELHO,
      verm(7, 0.35, 0.3),
      verm(9, 0.4, 0.5),
      verm(10, 0.45, 0.76),
      verm(4, 0.8, 0.58),
    ],
    bola: 'a7',
    passos: [
      {
        pergunta: '1/2 · Você é o 7, com a bola. O que fazer primeiro?',
        opcoes: [
          {
            id: 'conduz',
            jogador: 'a7',
            acao: 'movimentacao',
            alvo: paraPonto(0.72, 0.42),
            rotulo: 'Conduzir para cima do 4',
            correta: true,
            explicacao: 'Indo para cima do único defensor, ele tem que escolher: sair em você ou ficar no 10.',
          },
          {
            id: 'cedo',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Passe já para o 10',
            correta: false,
            explicacao: 'Tocando cedo, o 4 só precisa se preocupar com o 10. Você desperdiça o 2 contra 1.',
          },
          {
            id: 'chute',
            jogador: 'a7',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar de longe',
            correta: false,
            explicacao: 'Longe demais: chute fácil para o goleiro.',
          },
        ],
        depois: [
          { jogador: 'b4', para: { x: 0.79, y: 0.4 } },
          { jogador: 'a10', para: { x: 0.78, y: 0.76 } },
        ],
      },
      {
        pergunta: '2/2 · O 4 saiu em você. E agora?',
        opcoes: [
          {
            id: 'toca',
            jogador: 'a7',
            acao: 'passe',
            alvo: paraJogador('a10'),
            rotulo: 'Passe para o 10',
            correta: true,
            explicacao: 'O 4 veio em você, então o 10 ficou livre, perto do gol: gol!',
          },
          {
            id: 'dribla',
            jogador: 'a7',
            acao: 'drible',
            alvo: paraPonto(0.86, 0.34),
            rotulo: 'Driblar o 4',
            correta: false,
            explicacao: 'Por que driblar se o 10 está livre? Arrisca perder a bola.',
          },
          {
            id: 'chuta',
            jogador: 'a7',
            acao: 'finalizacao',
            alvo: GOL,
            rotulo: 'Chutar',
            correta: false,
            explicacao: 'Com o 4 bem na frente, o chute bate nele.',
          },
        ],
      },
    ],
    dica: 'Atraia o defensor primeiro, depois solte a bola.',
    conceito: 'No 2 CONTRA 1, leve a bola para cima do defensor. Quando ele sair em você, toque para o companheiro livre. Se ele não sair, siga e chute.',
    rating: 1050,
  },
  {
    id: 'recomposicao',
    titulo: 'Perdeu? Volta!',
    dificuldade: 'intermediario',
    categoria: 'transicao',
    contexto: 'Você perdeu a bola no ataque. O 10 vermelho vai sair no contra-ataque.',
    jogadores: [
      GOLEIRO_AZUL,
      azul(4, 0.3, 0.35),
      azul(5, 0.32, 0.72),
      azul(6, 0.65, 0.45),
      azul(9, 0.8, 0.6),
      GOLEIRO_VERMELHO,
      verm(10, 0.55, 0.5),
      verm(7, 0.48, 0.2),
      verm(9, 0.45, 0.82),
      verm(4, 0.85, 0.4),
    ],
    bola: 'b10',
    passos: [
      {
        pergunta: 'Você é o 6, que perdeu a bola. O que fazer?',
        opcoes: [
          {
            id: 'volta',
            jogador: 'a6',
            acao: 'movimentacao',
            alvo: paraPonto(0.3, 0.52),
            rotulo: 'Voltar correndo pelo meio',
            correta: true,
            explicacao: 'Voltando rápido pelo meio, você fica de novo entre a bola e o seu gol e fecha o caminho.',
          },
          {
            id: 'carrinho',
            jogador: 'a6',
            acao: 'desarme',
            alvo: paraJogador('b10'),
            rotulo: 'Dar um carrinho por trás',
            correta: false,
            explicacao: 'Carrinho por trás é falta e pode machucar o colega.',
            consequencia: 'Falta e cartão.',
          },
          {
            id: 'espera',
            jogador: 'a6',
            acao: 'movimentacao',
            alvo: paraPonto(0.72, 0.3),
            rotulo: 'Esperar a bola voltar',
            correta: false,
            explicacao: 'Parado lá na frente, seu time defende com um a menos.',
          },
        ],
      },
    ],
    dica: 'Para onde a bola está indo? Chegue lá antes dela.',
    conceito: 'Perdeu a bola? Todo mundo VOLTA rápido para trás da linha da bola, pelo meio. No futsal, o contra-ataque é muito rápido: os primeiros segundos decidem.',
    rating: 950,
  },
]
